name: Tesla Model X
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74049
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The long road to my Tesla Model X
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cadcd0'
    - '#96ac9f'
    - '#434629'
    - '#ae6456'
    - '#ba8a73'
  brandStrength: 0.5625
  lightness: 0.3437281
  saturation: 0.625
  rhythmicContrast: 0.1923495
purpose: []
