name: Tesla Model X
favicon: null
layout_spectrum: 0.75791
typography_spectrum: 0.74049
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The long road to my Tesla Model X
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0a0c'
    - '#825967'
    - '#f90024'
    - '#b1968d'
  brandStrength: 0.375
  lightness: 0.3437281
  saturation: 0.3125
  rhythmicContrast: 0.1923495
purpose: []
