layout_spectrum: 0.7905208
color:
  saturation: 0.6726773
  brandStrength: 0.3492304
  lightness: 0.3437281
  brandColors:
    - '#20283A'
    - '#CEC5BE'
    - '#ADA19A'
    - '#5C4C41'
    - '#92ABCE'
  rhythmicContrast: 0.1923495
typography_spectrum: 0.1894474
name: Tesla Model X
