name: Tesla Model X
favicon: null
layout_spectrum: 0.76333
typography_spectrum: 0.92658
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The long road to my Tesla Model X
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#cc0101'
    - '#00aff0'
    - '#de5d5d'
  brandStrength: 0.875
  lightness: 0.3437281
  saturation: 0.3125
  rhythmicContrast: 0.1923495
purpose: []
